### ISSUE TITLE
Issues about cutout

### ISSUE THREAD

**Issue by haohang96** [hologerry/SoCo#3] opened 2021-11-04 18:12 UTC
In **getitem** func of class **ImageFolderImageAsymBboxAwareMultiJitter1Cutout**:

the cutout is used : **img2_cutout = self.transform[7](img2, resized_bboxs2)**.

however, if flip operation is applied, the **resized_bboxs2** is not aligned with **bboxs2** and **img2**, is it a bug?

Does it should be **img2_cutout = self.transform[7](img2, _flip_box_(resized_bboxs2))** ? (_flip_box_ is just a pseudo func)

**Comment by hologerry** [comment] 2021-11-06 08:28
Hi, Thanks @haohang96 
The issue is addressed in the latest commit 20cd0e1bba4429f3055abd9b901ffff932ae1851.

**Closed by hologerry** 2021-11-06 08:28 UTC
